// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Blog struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type DeleteBlog struct {
	BlogID string `json:"blogId"`
}

type EditBlog struct {
	BlogID  string `json:"blogId"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type NewBlog struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}
